# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  uiSource: '/src'
  uiBuild: '${uiSource}/build'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pushd ${uiSource}
    npm install
    npm run build-prod
    popd
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'npm install and build-prod'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(1d1b4b0f-60eb-4a8f-aec2-48838d2c5c8e)'
    appType: 'webApp'
    WebAppName: 'ey-badging'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'